name: lab09
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/animales/

  fonts:
    - family: Jersey25Charted
      fonts:
        - asset: fonts/DancingScript-VariableFont_wght.ttf
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-VariableFont_wght.ttf
    - family: PoetsenOne
      fonts:
        - asset: fonts/PoetsenOne-Regular.ttf
